# Generated by Django 5.2.5 on 2025-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
