# Generated by Django 5.2.5 on 2025-09-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cont_name',
            new_name='name',
        ),
    ]
