# Generated by Django 5.2.5 on 2025-09-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='prince',
            new_name='price',
        ),
    ]
