# Generated by Django 5.2.5 on 2025-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_name', models.CharField(max_length=60)),
                ('location_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=40)),
                ('price_per_hour', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
