# Generated by Django 5.2.5 on 2025-09-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grounds',
            options={'verbose_name_plural': 'Grounds'},
        ),
        migrations.AddField(
            model_name='grounds',
            name='photo',
            field=models.ImageField(null=True, upload_to='ground/'),
        ),
    ]
