# Generated by Django 5.2.5 on 2025-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0002_alter_grounds_options_grounds_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
